# Copyright (c) IncQuery Labs cPlc.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# The following secrets need to be defined: INCQUERY_USERNAME, INCQUERY_PASSWORD, INCQUERY_AUTOSAR_UML_INTEGRATION_LICENSE

on:
  push
jobs:
  AutosarUml:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      
      - name: Backup current model
        run: |
          Copy-Item -Path ./counting-logic.qeax -Destination '${{ runner.temp }}/counting-logic-old.qeax'
      
      - name: Run IncQuery AUTOSAR-UML Bridge
        uses: ./
        with:
          arxml_folder_path: example-arxml
          ea_model_file_path: counting-logic.qeax
          incquery_username: "${{ secrets.INCQUERY_USERNAME }}"
          incquery_password: "${{ secrets.INCQUERY_PASSWORD }}"
          license: "${{ secrets.INCQUERY_AUTOSAR_UML_INTEGRATION_LICENSE }}"
