# Copyright (c) IncQuery Labs cPlc.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# The following secrets need to be defined: INCQUERY_USERNAME, INCQUERY_PASSWORD, INCQUERY_AUTOSAR_UML_INTEGRATION_LICENSE
name: AUTOSAR-UML Bridge Action Example

on:
  push:
    paths:
      - 'example-arxml/**/*.arxml'
jobs:
  AutosarUml:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      
      - name: Backup EA Project File
        id: backupEAProjectFile
        run: |
          $eaFileName = "counting-logic"
          $eaFileExtension = "qeax"
          $originalEaProjectFile = '${{ runner.temp }}/' + $eaFileName + '-old.' + $eaFileExtension
          $reimportedEaProjectFile = '.\' + $eaFileName + '.' + $eaFileExtension
          Copy-Item -Path $reimportedEaProjectFile -Destination $originalEaProjectFile
          echo "originalEAProjectFile=$originalEaProjectFile" >> $env:GITHUB_OUTPUT
          echo "reimportedEAProjectFile=$reimportedEaProjectFile" >> $env:GITHUB_OUTPUT
          echo "fileName=$eaFileName" >> $env:GITHUB_OUTPUT
          echo "fileExtension=$eaFileExtension" >> $env:GITHUB_OUTPUT
      
      - name: Run IncQuery AUTOSAR-UML Bridge
        uses: IncQueryLabs/incquery-suite-bridge-autosar-uml-action@v1
        with:
          arxml_folder_path: example-arxml
          ea_model_file_path: "${{steps.backupEAProjectFile.outputs.reimportedEAProjectFile}}"
          incquery_username: "${{ secrets.INCQUERY_USERNAME }}"
          incquery_password: "${{ secrets.INCQUERY_PASSWORD }}"
          license: "${{ secrets.INCQUERY_AUTOSAR_UML_INTEGRATION_LICENSE }}"
      - name: Push updated model
        run: |
          git config --local user.name "Automatic Model Update"
          git config --local user.email "username@users.noreply.github.com"
          git add '${{steps.backupEAProjectFile.outputs.reimportedEAProjectFile}}'
          git commit -m "Automatic Model Update"
          git push
